services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_NAME=irrigation
      - DB_USER=irrigation_user
      - DB_PASSWORD=development_password
    depends_on:
      - postgres
      - mosquitto
      - redis

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=irrigation
      - POSTGRES_USER=irrigation_user
      - POSTGRES_PASSWORD=development_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  mosquitto_data:
  mosquitto_log:
